### ISSUE TITLE
topic per group address

### ISSUE THREAD

**Issue by avestnik** [contactless/wb-mqtt-knx#4]
коллеги, добрый день. можно ли сделать доработку, чтобы в дополнение к отправке в типк knx/data сообщения, полученные с шины, отправлялись еще в и топики вида knx/1/1/2, где 1/1/2 -- это групповой адрес?

**Comment by sikmir** [comment]
Это можно сделать таким правилом:
```js
trackMqtt("/devices/knx/controls/data", function(message) {
  var msg = message.value.split(/\s+/);
  publish("/knx/{}".format(msg[1].slice(2)), msg[3], 2, true);
});
```
